Vagrant.configure("2") do |config|
  config.vm.box = "spox/ubuntu-arm"
  config.vm.box_version = "1.0.0"
  config.vm.network "private_network", ip: "192.168.10.12"
# config.vm.network "public_network"
# config.vm.synced_folder "/Users/satishankalap/Desktop/Resume", "/vagrant/sync_data" 
  config.vm.provider "vmware_desktop" do |vmware|
    vmware.gui = true
    vmware.allowlist_verified = true
    vmware.memory="1600"
    vmware.cpus=2
  end
#Provisioning
  config.vm.provision "shell" , inline: <<-SHELL 
    apt-get update  
    apt-get install apache2 -y 
  SHELL
  end
